print("'Hello, World!'")
print("Jawad")
print("Jawad Malik")
print("1,2,3")
print("Hello \nWorld")
print("Hello\tWorld")
print("Pakistan,Iran,China")
print("'7-8-6'")
print("'Welcome Home'")
print("'12'")
print('He said, "Hello!"')
print(r'This is a backslash: \.')
print("'I am 27 years old'")
print("'The temperature is 19'")
print(1) 
print(1+1)
print(1+2)
print(1+3)
print(1+4)